version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed"
  build:
    commands:
      - echo "Preparing static website files"
artifacts:
  files:
    - 'src/main/webapp/**/*'
  base-directory: 'src/main/webapp'
