apiVersion: apps/v1
kind: Deployment
metadata:
  name: sravan-web
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: sravan-web
  template:
    metadata:
      labels:
        app: sravan-web
    spec:
      containers:
        - name: sravan-web
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
